################################################################################
#
# fastfetch
#
################################################################################

FASTFETCH_VERSION = 2.66.0
FASTFETCH_SITE = $(call github,fastfetch-cli,fastfetch,$(FASTFETCH_VERSION))
FASTFETCH_LICENSE = MIT
FASTFETCH_LICENSE_FILES = LICENSE

FASTFETCH_CONF_OPTS = \
	-DBUILD_FLASHFETCH=OFF \
	-DBUILD_TESTS=OFF \
	-DINSTALL_LICENSE=OFF \
	-DSET_TWEAK=OFF \
	-DENABLE_ASAN=OFF \
	-DENABLE_CHAFA=OFF \
	-DENABLE_DBUS=OFF \
	-DENABLE_DCONF=OFF \
	-DENABLE_DDCUTIL=OFF \
	-DENABLE_DRM=OFF \
	-DENABLE_EET=OFF \
	-DENABLE_EGL=OFF \
	-DENABLE_ELF=OFF \
	-DENABLE_EMBEDDED_AMDGPUIDS=OFF \
	-DENABLE_EMBEDDED_PCIIDS=OFF \
	-DENABLE_GIO=OFF \
	-DENABLE_GLX=OFF \
	-DENABLE_IMAGEMAGICK6=OFF \
	-DENABLE_IMAGEMAGICK7=OFF \
	-DENABLE_LIBZFS=OFF \
	-DENABLE_LTO=OFF \
	-DENABLE_LUA=OFF \
	-DENABLE_OPENCL=OFF \
	-DENABLE_PULSE=OFF \
	-DENABLE_QUICKJS=OFF \
	-DENABLE_RPM=OFF \
	-DENABLE_SQLITE3=OFF \
	-DENABLE_SYSTEM_YYJSON=OFF \
	-DENABLE_TRACER=OFF \
	-DENABLE_VADRM=OFF \
	-DENABLE_VAX11=OFF \
	-DENABLE_VDPAU=OFF \
	-DENABLE_VULKAN=OFF \
	-DENABLE_WAYLAND=OFF \
	-DENABLE_XCB_RANDR=OFF \
	-DENABLE_XRANDR=OFF \
	-DENABLE_ZLIB=OFF \
	-DDEFAULT_STRUCTURE=Title:Separator:OS:Host:Kernel:Uptime:CPU:Memory:Disk:LocalIp:Break:Colors

$(eval $(cmake-package))
